-- [03c] Emission Factors — TGO 2569 FULL (~190 rows)
-- Generated by docs/sql/generate_ef_full.py
USE control_z_v2;

DELETE FROM emission_factors;

INSERT INTO emission_factors (
  source_id, category_id, gas_id, activity_name_th, activity_subtype,
  co2_type, ef_purpose, ef_value, ef_unit, ef_unit_numerator, ef_unit_denominator,
  region, is_default, effective_from, effective_until
)
SELECT
  (SELECT source_id FROM ef_sources WHERE source_code = r.src),
  c.category_id,
  g.gas_id,
  COALESCE(r.name_th, c.name_th),
  r.sub,
  r.co2,
  r.purpose,
  r.val,
  r.unit,
  r.num,
  r.den,
  'Thailand',
  r.is_def,
  r.eff_from,
  r.until
FROM (
  SELECT 'FUEL_NATGAS_NCV_SCF' AS cat, 'CO2' AS gas, 0.05720000 AS val, 'kgCO2/scf' AS unit, 'kgCO2' AS num, 'scf' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_NATGAS_NCV_SCF' AS cat, 'CH4_FOSSIL' AS gas, 0.00000102 AS val, 'kgCH4/scf' AS unit, 'kgCH4' AS num, 'scf' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_NATGAS_NCV_SCF' AS cat, 'N2O' AS gas, 0.00000010 AS val, 'kgN2O/scf' AS unit, 'kgN2O' AS num, 'scf' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_NATGAS_NCV_MJ' AS cat, 'CO2' AS gas, 0.05610000 AS val, 'kgCO2/MJ' AS unit, 'kgCO2' AS num, 'MJ' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_NATGAS_NCV_MJ' AS cat, 'CH4_FOSSIL' AS gas, 0.00000100 AS val, 'kgCH4/MJ' AS unit, 'kgCH4' AS num, 'MJ' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_NATGAS_NCV_MJ' AS cat, 'N2O' AS gas, 0.00000010 AS val, 'kgN2O/MJ' AS unit, 'kgN2O' AS num, 'MJ' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_NATGAS_HHV_MJ' AS cat, 'CO2' AS gas, 0.05010000 AS val, 'kgCO2/MJ' AS unit, 'kgCO2' AS num, 'MJ' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_NATGAS_HHV_MJ' AS cat, 'CH4_FOSSIL' AS gas, 0.00000100 AS val, 'kgCH4/MJ' AS unit, 'kgCH4' AS num, 'MJ' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_NATGAS_HHV_MJ' AS cat, 'N2O' AS gas, 0.00000010 AS val, 'kgN2O/MJ' AS unit, 'kgN2O' AS num, 'MJ' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_NATGAS_HHV_MMBTU' AS cat, 'CO2' AS gas, 52.90000000 AS val, 'kgCO2/MMBTU' AS unit, 'kgCO2' AS num, 'MMBTU' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_NATGAS_HHV_MMBTU' AS cat, 'CH4_FOSSIL' AS gas, 0.00100000 AS val, 'kgCH4/MMBTU' AS unit, 'kgCH4' AS num, 'MMBTU' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_NATGAS_HHV_MMBTU' AS cat, 'N2O' AS gas, 0.00010000 AS val, 'kgN2O/MMBTU' AS unit, 'kgN2O' AS num, 'MMBTU' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_LPG_LITRE' AS cat, 'CO2' AS gas, 1.67970000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_LPG_LITRE' AS cat, 'CH4_FOSSIL' AS gas, 0.00002660 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_LPG_LITRE' AS cat, 'N2O' AS gas, 0.00000266 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_LPG_KG' AS cat, 'CO2' AS gas, 3.11060000 AS val, 'kgCO2/kg' AS unit, 'kgCO2' AS num, 'kg' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_LPG_KG' AS cat, 'CH4_FOSSIL' AS gas, 0.00004930 AS val, 'kgCH4/kg' AS unit, 'kgCH4' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_LPG_KG' AS cat, 'N2O' AS gas, 0.00000493 AS val, 'kgN2O/kg' AS unit, 'kgN2O' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_FUELOIL_A' AS cat, 'CO2' AS gas, 3.20970000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_FUELOIL_A' AS cat, 'CH4_FOSSIL' AS gas, 0.00012400 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_FUELOIL_A' AS cat, 'N2O' AS gas, 0.00002490 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_FUELOIL_C' AS cat, 'CO2' AS gas, 3.23530000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_FUELOIL_C' AS cat, 'CH4_FOSSIL' AS gas, 0.00012500 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_FUELOIL_C' AS cat, 'N2O' AS gas, 0.00002510 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_KEROSENE_JET' AS cat, 'CO2' AS gas, 2.46890000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_KEROSENE_JET' AS cat, 'CH4_FOSSIL' AS gas, 0.00010400 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_KEROSENE_JET' AS cat, 'N2O' AS gas, 0.00002070 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_KEROSENE_OTHER' AS cat, 'CO2' AS gas, 2.48270000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_KEROSENE_OTHER' AS cat, 'CH4_FOSSIL' AS gas, 0.00010400 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_KEROSENE_OTHER' AS cat, 'N2O' AS gas, 0.00002070 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_DIESEL' AS cat, 'CO2' AS gas, 2.69870000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_DIESEL' AS cat, 'CH4_FOSSIL' AS gas, 0.00010900 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_DIESEL' AS cat, 'N2O' AS gas, 0.00002190 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_GASOLINE' AS cat, 'CO2' AS gas, 2.18160000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_GASOLINE' AS cat, 'CH4_FOSSIL' AS gas, 0.00009440 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_GASOLINE' AS cat, 'N2O' AS gas, 0.00001890 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_LIGNITE' AS cat, 'CO2' AS gas, 1.20190000 AS val, 'kgCO2/kg' AS unit, 'kgCO2' AS num, 'kg' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_LIGNITE' AS cat, 'CH4_FOSSIL' AS gas, 0.00010500 AS val, 'kgCH4/kg' AS unit, 'kgCH4' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_LIGNITE' AS cat, 'N2O' AS gas, 0.00001570 AS val, 'kgN2O/kg' AS unit, 'kgN2O' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_ANTHRACITE' AS cat, 'CO2' AS gas, 3.08660000 AS val, 'kgCO2/kg' AS unit, 'kgCO2' AS num, 'kg' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_ANTHRACITE' AS cat, 'CH4_FOSSIL' AS gas, 0.00031400 AS val, 'kgCH4/kg' AS unit, 'kgCH4' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_ANTHRACITE' AS cat, 'N2O' AS gas, 0.00004710 AS val, 'kgN2O/kg' AS unit, 'kgN2O' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_COAL_BITUMINOUS' AS cat, 'CO2' AS gas, 2.49460000 AS val, 'kgCO2/kg' AS unit, 'kgCO2' AS num, 'kg' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_COAL_BITUMINOUS' AS cat, 'CH4_FOSSIL' AS gas, 0.00030000 AS val, 'kgCH4/kg' AS unit, 'kgCH4' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_COAL_BITUMINOUS' AS cat, 'N2O' AS gas, 0.00000000 AS val, 'kgN2O/kg' AS unit, 'kgN2O' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_COAL_COKING' AS cat, 'CO2' AS gas, 2.61380000 AS val, 'kgCO2/kg' AS unit, 'kgCO2' AS num, 'kg' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_COAL_COKING' AS cat, 'CH4_FOSSIL' AS gas, 0.00030000 AS val, 'kgCH4/kg' AS unit, 'kgCH4' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_COAL_COKING' AS cat, 'N2O' AS gas, 0.00000000 AS val, 'kgN2O/kg' AS unit, 'kgN2O' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_COAL_SUBBIT' AS cat, 'CO2' AS gas, 2.53000000 AS val, 'kgCO2/kg' AS unit, 'kgCO2' AS num, 'kg' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_COAL_SUBBIT' AS cat, 'CH4_FOSSIL' AS gas, 0.00002640 AS val, 'kgCH4/kg' AS unit, 'kgCH4' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_COAL_SUBBIT' AS cat, 'N2O' AS gas, 0.00003960 AS val, 'kgN2O/kg' AS unit, 'kgN2O' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_ACETYLENE' AS cat, 'CO2' AS gas, 3.38460000 AS val, 'kgCO2/kg' AS unit, 'kgCO2' AS num, 'kg' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_ETHANE' AS cat, 'CO2' AS gas, 3.14290000 AS val, 'kgCO2/kg' AS unit, 'kgCO2' AS num, 'kg' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_PROPANE' AS cat, 'CO2' AS gas, 3.00000000 AS val, 'kgCO2/kg' AS unit, 'kgCO2' AS num, 'kg' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_BUTANE' AS cat, 'CO2' AS gas, 3.03450000 AS val, 'kgCO2/kg' AS unit, 'kgCO2' AS num, 'kg' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_BIODIESEL' AS cat, 'CO2' AS gas, 1.64400000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_BIODIESEL' AS cat, 'CH4' AS gas, 0.00010000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_BIODIESEL' AS cat, 'N2O' AS gas, 0.00000000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_BIOGASOLINE' AS cat, 'CO2' AS gas, 1.49680000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_BIOGASOLINE' AS cat, 'CH4' AS gas, 0.00010000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_BIOGASOLINE' AS cat, 'N2O' AS gas, 0.00000000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_WOOD' AS cat, 'CH4' AS gas, 0.00048000 AS val, 'kgCH4/kg' AS unit, 'kgCH4' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_WOOD' AS cat, 'N2O' AS gas, 0.00006400 AS val, 'kgN2O/kg' AS unit, 'kgN2O' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_WOOD_BIO' AS cat, 'CO2_BIO' AS gas, 1.79090000 AS val, 'kgCO2bio/kg' AS unit, 'kgCO2bio' AS num, 'kg' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_SAWDUST' AS cat, 'CH4' AS gas, 0.00030000 AS val, 'kgCH4/kg' AS unit, 'kgCH4' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_SAWDUST' AS cat, 'N2O' AS gas, 0.00000000 AS val, 'kgN2O/kg' AS unit, 'kgN2O' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_SAWDUST_BIO' AS cat, 'CO2_BIO' AS gas, 1.21860000 AS val, 'kgCO2bio/kg' AS unit, 'kgCO2bio' AS num, 'kg' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_CHARCOAL' AS cat, 'CH4' AS gas, 0.00580000 AS val, 'kgCH4/kg' AS unit, 'kgCH4' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_CHARCOAL' AS cat, 'N2O' AS gas, 0.00010000 AS val, 'kgN2O/kg' AS unit, 'kgN2O' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_CHARCOAL_BIO' AS cat, 'CO2_BIO' AS gas, 3.23460000 AS val, 'kgCO2bio/kg' AS unit, 'kgCO2bio' AS num, 'kg' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_PADDYHUSK' AS cat, 'CH4' AS gas, 0.00040000 AS val, 'kgCH4/kg' AS unit, 'kgCH4' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_PADDYHUSK' AS cat, 'N2O' AS gas, 0.00010000 AS val, 'kgN2O/kg' AS unit, 'kgN2O' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_PADDYHUSK_BIO' AS cat, 'CO2_BIO' AS gas, 1.44000000 AS val, 'kgCO2bio/kg' AS unit, 'kgCO2bio' AS num, 'kg' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_BAGASSE' AS cat, 'CH4' AS gas, 0.00022600 AS val, 'kgCH4/kg' AS unit, 'kgCH4' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_BAGASSE' AS cat, 'N2O' AS gas, 0.00003010 AS val, 'kgN2O/kg' AS unit, 'kgN2O' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_BAGASSE_BIO' AS cat, 'CO2_BIO' AS gas, 0.75300000 AS val, 'kgCO2bio/kg' AS unit, 'kgCO2bio' AS num, 'kg' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_PALMSHELL' AS cat, 'CH4' AS gas, 0.00055600 AS val, 'kgCH4/kg' AS unit, 'kgCH4' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_PALMSHELL' AS cat, 'N2O' AS gas, 0.00007410 AS val, 'kgN2O/kg' AS unit, 'kgN2O' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_PALMSHELL_BIO' AS cat, 'CO2_BIO' AS gas, 1.85300000 AS val, 'kgCO2bio/kg' AS unit, 'kgCO2bio' AS num, 'kg' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_COB' AS cat, 'CH4' AS gas, 0.00050300 AS val, 'kgCH4/kg' AS unit, 'kgCH4' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_COB' AS cat, 'N2O' AS gas, 0.00006710 AS val, 'kgN2O/kg' AS unit, 'kgN2O' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_COB_BIO' AS cat, 'CO2_BIO' AS gas, 1.67800000 AS val, 'kgCO2bio/kg' AS unit, 'kgCO2bio' AS num, 'kg' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_BIOGAS' AS cat, 'CH4' AS gas, 0.00002090 AS val, 'kgCH4/m3' AS unit, 'kgCH4' AS num, 'm3' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_BIOGAS' AS cat, 'N2O' AS gas, 0.00000209 AS val, 'kgN2O/m3' AS unit, 'kgN2O' AS num, 'm3' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_BIOGAS_BIO' AS cat, 'CO2_BIO' AS gas, 1.14280000 AS val, 'kgCO2bio/m3' AS unit, 'kgCO2bio' AS num, 'm3' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_DIESEL_B7' AS cat, 'CO2' AS gas, 2.50980000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_DIESEL_B7' AS cat, 'CH4_FOSSIL' AS gas, 0.00010000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_DIESEL_B7' AS cat, 'N2O' AS gas, 0.00000000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_DIESEL_B20' AS cat, 'CO2' AS gas, 2.15900000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_DIESEL_B20' AS cat, 'CH4_FOSSIL' AS gas, 0.00010000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_DIESEL_B20' AS cat, 'N2O' AS gas, 0.00000000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_GASOHOL_E10' AS cat, 'CO2' AS gas, 1.96340000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_GASOHOL_E10' AS cat, 'CH4_FOSSIL' AS gas, 0.00010000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_GASOHOL_E10' AS cat, 'N2O' AS gas, 0.00000000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_GASOHOL_E20' AS cat, 'CO2' AS gas, 1.74530000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_GASOHOL_E20' AS cat, 'CH4_FOSSIL' AS gas, 0.00010000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_GASOHOL_E20' AS cat, 'N2O' AS gas, 0.00000000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_GASOHOL_E85' AS cat, 'CO2' AS gas, 0.32720000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_GASOHOL_E85' AS cat, 'CH4_FOSSIL' AS gas, 0.00010000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_GASOHOL_E85' AS cat, 'N2O' AS gas, 0.00000000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_DIESEL_B7_BIO' AS cat, 'CO2_BIO' AS gas, 0.11510000 AS val, 'kgCO2bio/litre' AS unit, 'kgCO2bio' AS num, 'litre' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_DIESEL_B20_BIO' AS cat, 'CO2_BIO' AS gas, 0.32880000 AS val, 'kgCO2bio/litre' AS unit, 'kgCO2bio' AS num, 'litre' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_GASOHOL_E10_BIO' AS cat, 'CO2_BIO' AS gas, 0.14970000 AS val, 'kgCO2bio/litre' AS unit, 'kgCO2bio' AS num, 'litre' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_GASOHOL_E20_BIO' AS cat, 'CO2_BIO' AS gas, 0.29940000 AS val, 'kgCO2bio/litre' AS unit, 'kgCO2bio' AS num, 'litre' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUEL_GASOHOL_E85_BIO' AS cat, 'CO2_BIO' AS gas, 1.27230000 AS val, 'kgCO2bio/litre' AS unit, 'kgCO2bio' AS num, 'litre' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_CNG' AS cat, 'CO2' AS gas, 2.12620000 AS val, 'kgCO2/kg' AS unit, 'kgCO2' AS num, 'kg' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_CNG' AS cat, 'CH4_FOSSIL' AS gas, 0.00349000 AS val, 'kgCH4/kg' AS unit, 'kgCH4' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_CNG' AS cat, 'N2O' AS gas, 0.00011400 AS val, 'kgN2O/kg' AS unit, 'kgN2O' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_LPG_KG' AS cat, 'CO2' AS gas, 3.11060000 AS val, 'kgCO2/kg' AS unit, 'kgCO2' AS num, 'kg' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_LPG_KG' AS cat, 'CH4_FOSSIL' AS gas, 0.00306000 AS val, 'kgCH4/kg' AS unit, 'kgCH4' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_LPG_KG' AS cat, 'N2O' AS gas, 0.00000986 AS val, 'kgN2O/kg' AS unit, 'kgN2O' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_LPG_L' AS cat, 'CO2' AS gas, 1.67970000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_LPG_L' AS cat, 'CH4_FOSSIL' AS gas, 0.00165000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_LPG_L' AS cat, 'N2O' AS gas, 0.00000532 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_DIESEL' AS cat, 'CO2' AS gas, 2.69870000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_DIESEL' AS cat, 'CH4_FOSSIL' AS gas, 0.00014200 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_DIESEL' AS cat, 'N2O' AS gas, 0.00014200 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_GAS_UNCNTRL' AS cat, 'CO2' AS gas, 2.18160000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_GAS_UNCNTRL' AS cat, 'CH4_FOSSIL' AS gas, 0.00104000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_GAS_UNCNTRL' AS cat, 'N2O' AS gas, 0.00010100 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_GAS_OXCAT' AS cat, 'CO2' AS gas, 2.18160000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_GAS_OXCAT' AS cat, 'CH4_FOSSIL' AS gas, 0.00078700 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_GAS_OXCAT' AS cat, 'N2O' AS gas, 0.00025200 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_GAS_LOWM' AS cat, 'CO2' AS gas, 2.18160000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_GAS_LOWM' AS cat, 'CH4_FOSSIL' AS gas, 0.00012000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_GAS_LOWM' AS cat, 'N2O' AS gas, 0.00017900 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_BIODIESEL' AS cat, 'CO2' AS gas, 1.64400000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_BIODIESEL' AS cat, 'CH4_FOSSIL' AS gas, 0.00010000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_BIODIESEL' AS cat, 'N2O' AS gas, 0.00010000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_ETHANOL' AS cat, 'CO2' AS gas, 1.49680000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_ETHANOL' AS cat, 'CH4' AS gas, 0.00040000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_B7' AS cat, 'CO2' AS gas, 2.50980000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_B7' AS cat, 'CH4_FOSSIL' AS gas, 0.00010000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_B7' AS cat, 'N2O' AS gas, 0.00010000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_B20' AS cat, 'CO2' AS gas, 2.15900000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_B20' AS cat, 'CH4_FOSSIL' AS gas, 0.00010000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_B20' AS cat, 'N2O' AS gas, 0.00010000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E10_OXCAT' AS cat, 'CO2' AS gas, 1.96340000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E10_OXCAT' AS cat, 'CH4_FOSSIL' AS gas, 0.00070000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E10_OXCAT' AS cat, 'N2O' AS gas, 0.00020000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E20_OXCAT' AS cat, 'CO2' AS gas, 1.74530000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E20_OXCAT' AS cat, 'CH4_FOSSIL' AS gas, 0.00070000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E20_OXCAT' AS cat, 'N2O' AS gas, 0.00020000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E85_OXCAT' AS cat, 'CO2' AS gas, 0.32720000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E85_OXCAT' AS cat, 'CH4_FOSSIL' AS gas, 0.00040000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E85_OXCAT' AS cat, 'N2O' AS gas, 0.00000000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E10_LOWM' AS cat, 'CO2' AS gas, 1.96340000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E10_LOWM' AS cat, 'CH4_FOSSIL' AS gas, 0.00010000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E10_LOWM' AS cat, 'N2O' AS gas, 0.00020000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E20_LOWM' AS cat, 'CO2' AS gas, 1.74530000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E20_LOWM' AS cat, 'CH4_FOSSIL' AS gas, 0.00020000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E20_LOWM' AS cat, 'N2O' AS gas, 0.00010000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E85_LOWM' AS cat, 'CO2' AS gas, 0.32720000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E85_LOWM' AS cat, 'CH4_FOSSIL' AS gas, 0.00030000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E85_LOWM' AS cat, 'N2O' AS gas, 0.00000000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_B7_BIO' AS cat, 'CO2_BIO' AS gas, 0.11510000 AS val, 'kgCO2bio/litre' AS unit, 'kgCO2bio' AS num, 'litre' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_B20_BIO' AS cat, 'CO2_BIO' AS gas, 0.32880000 AS val, 'kgCO2bio/litre' AS unit, 'kgCO2bio' AS num, 'litre' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E10_OXCAT_BIO' AS cat, 'CO2_BIO' AS gas, 0.14970000 AS val, 'kgCO2bio/litre' AS unit, 'kgCO2bio' AS num, 'litre' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E20_OXCAT_BIO' AS cat, 'CO2_BIO' AS gas, 0.29940000 AS val, 'kgCO2bio/litre' AS unit, 'kgCO2bio' AS num, 'litre' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E85_OXCAT_BIO' AS cat, 'CO2_BIO' AS gas, 1.27230000 AS val, 'kgCO2bio/litre' AS unit, 'kgCO2bio' AS num, 'litre' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E10_LOWM_BIO' AS cat, 'CO2_BIO' AS gas, 0.14970000 AS val, 'kgCO2bio/litre' AS unit, 'kgCO2bio' AS num, 'litre' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E20_LOWM_BIO' AS cat, 'CO2_BIO' AS gas, 0.29940000 AS val, 'kgCO2bio/litre' AS unit, 'kgCO2bio' AS num, 'litre' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_ONROAD_E85_LOWM_BIO' AS cat, 'CO2_BIO' AS gas, 1.27230000 AS val, 'kgCO2bio/litre' AS unit, 'kgCO2bio' AS num, 'litre' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_LPG_KG' AS cat, 'CO2' AS gas, 3.11060000 AS val, 'kgCO2/kg' AS unit, 'kgCO2' AS num, 'kg' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_LPG_KG' AS cat, 'CH4_FOSSIL' AS gas, 0.00250000 AS val, 'kgCH4/kg' AS unit, 'kgCH4' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_LPG_KG' AS cat, 'N2O' AS gas, 0.00010000 AS val, 'kgN2O/kg' AS unit, 'kgN2O' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_DIESEL' AS cat, 'CO2' AS gas, 2.69870000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, 'Agriculture' AS sub, 'ดีเซลนอกถนน (Agriculture)' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_DIESEL' AS cat, 'CH4_FOSSIL' AS gas, 0.00015100 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, 'Agriculture' AS sub, 'ดีเซลนอกถนน (Agriculture)' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_DIESEL' AS cat, 'N2O' AS gas, 0.00104000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, 'Agriculture' AS sub, 'ดีเซลนอกถนน (Agriculture)' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_DIESEL' AS cat, 'CO2' AS gas, 2.69870000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, 'Forestry' AS sub, 'ดีเซลนอกถนน (Forestry)' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_DIESEL' AS cat, 'CH4_FOSSIL' AS gas, 0.00015100 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, 'Forestry' AS sub, 'ดีเซลนอกถนน (Forestry)' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_DIESEL' AS cat, 'N2O' AS gas, 0.00104000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, 'Forestry' AS sub, 'ดีเซลนอกถนน (Forestry)' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_DIESEL' AS cat, 'CO2' AS gas, 2.69870000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, 'Industry' AS sub, 'ดีเซลนอกถนน (Industry)' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_DIESEL' AS cat, 'CH4_FOSSIL' AS gas, 0.00015100 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, 'Industry' AS sub, 'ดีเซลนอกถนน (Industry)' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_DIESEL' AS cat, 'N2O' AS gas, 0.00104000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, 'Industry' AS sub, 'ดีเซลนอกถนน (Industry)' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_DIESEL' AS cat, 'CO2' AS gas, 2.69870000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, 'Household' AS sub, 'ดีเซลนอกถนน (Household)' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_DIESEL' AS cat, 'CH4_FOSSIL' AS gas, 0.00015100 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, 'Household' AS sub, 'ดีเซลนอกถนน (Household)' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_DIESEL' AS cat, 'N2O' AS gas, 0.00104000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, 'Household' AS sub, 'ดีเซลนอกถนน (Household)' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_BIODIESEL' AS cat, 'CO2' AS gas, 1.64400000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_ETHANOL' AS cat, 'CO2' AS gas, 1.49680000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS4ST' AS cat, 'CO2' AS gas, 2.18160000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, 'Agriculture' AS sub, 'เบนซิน 4-stroke (Agriculture)' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS4ST' AS cat, 'CH4_FOSSIL' AS gas, 0.00252000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, 'Agriculture' AS sub, 'เบนซิน 4-stroke (Agriculture) CH4' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS4ST' AS cat, 'N2O' AS gas, 0.00006300 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, 'Agriculture' AS sub, 'เบนซิน 4-stroke (Agriculture) N2O' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS4ST' AS cat, 'CO2' AS gas, 2.18160000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, 'Forestry' AS sub, 'เบนซิน 4-stroke (Forestry)' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS4ST' AS cat, 'CH4_FOSSIL' AS gas, 0.00000000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, 'Forestry' AS sub, 'เบนซิน 4-stroke (Forestry) CH4' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS4ST' AS cat, 'N2O' AS gas, 0.00000000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, 'Forestry' AS sub, 'เบนซิน 4-stroke (Forestry) N2O' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS4ST' AS cat, 'CO2' AS gas, 2.18160000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, 'Industry' AS sub, 'เบนซิน 4-stroke (Industry)' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS4ST' AS cat, 'CH4_FOSSIL' AS gas, 0.00157000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, 'Industry' AS sub, 'เบนซิน 4-stroke (Industry) CH4' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS4ST' AS cat, 'N2O' AS gas, 0.00006300 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, 'Industry' AS sub, 'เบนซิน 4-stroke (Industry) N2O' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS4ST' AS cat, 'CO2' AS gas, 2.18160000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, 'Household' AS sub, 'เบนซิน 4-stroke (Household)' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS4ST' AS cat, 'CH4_FOSSIL' AS gas, 0.00378000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, 'Household' AS sub, 'เบนซิน 4-stroke (Household) CH4' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS4ST' AS cat, 'N2O' AS gas, 0.00006300 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, 'Household' AS sub, 'เบนซิน 4-stroke (Household) N2O' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS2ST' AS cat, 'CO2' AS gas, 2.18160000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, 'Agriculture' AS sub, 'เบนซิน 2-stroke (Agriculture)' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS2ST' AS cat, 'CH4_FOSSIL' AS gas, 0.00441000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, 'Agriculture' AS sub, 'เบนซิน 2-stroke (Agriculture) CH4' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS2ST' AS cat, 'N2O' AS gas, 0.00001260 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, 'Agriculture' AS sub, 'เบนซิน 2-stroke (Agriculture) N2O' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS2ST' AS cat, 'CO2' AS gas, 2.18160000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, 'Forestry' AS sub, 'เบนซิน 2-stroke (Forestry)' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS2ST' AS cat, 'CH4_FOSSIL' AS gas, 0.00535000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, 'Forestry' AS sub, 'เบนซิน 2-stroke (Forestry) CH4' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS2ST' AS cat, 'N2O' AS gas, 0.00001260 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, 'Forestry' AS sub, 'เบนซิน 2-stroke (Forestry) N2O' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS2ST' AS cat, 'CO2' AS gas, 2.18160000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, 'Industry' AS sub, 'เบนซิน 2-stroke (Industry)' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS2ST' AS cat, 'CH4_FOSSIL' AS gas, 0.00409000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, 'Industry' AS sub, 'เบนซิน 2-stroke (Industry) CH4' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS2ST' AS cat, 'N2O' AS gas, 0.00001260 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, 'Industry' AS sub, 'เบนซิน 2-stroke (Industry) N2O' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS2ST' AS cat, 'CO2' AS gas, 2.18160000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, 'Household' AS sub, 'เบนซิน 2-stroke (Household)' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS2ST' AS cat, 'CH4_FOSSIL' AS gas, 0.00567000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, 'Household' AS sub, 'เบนซิน 2-stroke (Household) CH4' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_GAS2ST' AS cat, 'N2O' AS gas, 0.00001260 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, 'Household' AS sub, 'เบนซิน 2-stroke (Household) N2O' AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_B7' AS cat, 'CO2' AS gas, 2.50980000 AS val, 'kgCO2/litre' AS unit, 'kgCO2' AS num, 'litre' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_B7' AS cat, 'CH4_FOSSIL' AS gas, 0.00020000 AS val, 'kgCH4/litre' AS unit, 'kgCH4' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_B7' AS cat, 'N2O' AS gas, 0.00100000 AS val, 'kgN2O/litre' AS unit, 'kgN2O' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'MOBILE_OFFROAD_B7_BIO' AS cat, 'CO2_BIO' AS gas, 0.11510000 AS val, 'kgCO2bio/litre' AS unit, 'kgCO2bio' AS num, 'litre' AS den, 'biogenic' AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'TGO_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUGITIVE_R22' AS cat, 'R22' AS gas, 1760.00000000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'IPCC_2013_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUGITIVE_R32' AS cat, 'R32' AS gas, 677.00000000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'IPCC_2013_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUGITIVE_R125' AS cat, 'R125' AS gas, 3170.00000000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'IPCC_2013_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUGITIVE_R134' AS cat, 'R134' AS gas, 1120.00000000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'IPCC_2013_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUGITIVE_R134A' AS cat, 'R134A' AS gas, 1300.00000000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'IPCC_2013_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUGITIVE_R143' AS cat, 'R143' AS gas, 328.00000000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'IPCC_2013_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUGITIVE_R143A' AS cat, 'R143A' AS gas, 4800.00000000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'IPCC_2013_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUGITIVE_R404A' AS cat, 'R404A' AS gas, 3942.80000000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'IPCC_2013_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUGITIVE_R407A' AS cat, 'R407A' AS gas, 1923.40000000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'IPCC_2013_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUGITIVE_R407C' AS cat, 'R407C' AS gas, 1624.21000000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'IPCC_2013_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'FUGITIVE_R410A' AS cat, 'R410A' AS gas, 1923.50000000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, NULL AS name_th, NULL AS purpose, 'IPCC_2013_AR5' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'ELEC_GRID_TH_2016_S2' AS cat, 'CO2' AS gas, 0.49990000 AS val, 'kgCO2/kWh' AS unit, 'kgCO2' AS num, 'kWh' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, 'cfo_scope2' AS purpose, 'THAI_LCI' AS src, '2026-01-01' AS eff_from, '2026-03-31' AS until, 0 AS is_def
  UNION ALL
  SELECT 'ELEC_GRID_TH_2016_S3' AS cat, 'CO2' AS gas, 0.09870000 AS val, 'kgCO2/kWh' AS unit, 'kgCO2' AS num, 'kWh' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, 'scope3_elec' AS purpose, 'THAI_LCI' AS src, '2026-01-01' AS eff_from, '2026-03-31' AS until, 0 AS is_def
  UNION ALL
  SELECT 'ELEC_GRID_TH_2016_CFP' AS cat, 'CO2' AS gas, 0.59860000 AS val, 'kgCO2/kWh' AS unit, 'kgCO2' AS num, 'kWh' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, 'cfp' AS purpose, 'THAI_LCI' AS src, '2026-01-01' AS eff_from, NULL AS until, 0 AS is_def
  UNION ALL
  SELECT 'ELEC_GRID_TH_2022_S2' AS cat, 'CO2' AS gas, 0.47500000 AS val, 'kgCO2/kWh' AS unit, 'kgCO2' AS num, 'kWh' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, 'cfo_scope2' AS purpose, 'THAI_LCI' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'ELEC_GRID_TH_2022_S3' AS cat, 'CO2' AS gas, 0.08120000 AS val, 'kgCO2/kWh' AS unit, 'kgCO2' AS num, 'kWh' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, 'scope3_elec' AS purpose, 'THAI_LCI' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'ELEC_GRID_TH_2022_CFP' AS cat, 'CO2' AS gas, 0.55620000 AS val, 'kgCO2/kWh' AS unit, 'kgCO2' AS num, 'kWh' AS den, 'fossil' AS co2, NULL AS sub, NULL AS name_th, 'cfp' AS purpose, 'THAI_LCI' AS src, '2026-01-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C1_PAPER' AS cat, 'CO2' AS gas, 2.10200000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, 'กระดาษ' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C1_INK' AS cat, 'CO2' AS gas, 4.52000000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, 'หมึกพิมพ์ / หมึกทั่วไป' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C1_WATER' AS cat, 'CO2' AS gas, 0.54100000 AS val, 'kgCO2eq/m3' AS unit, 'kgCO2eq' AS num, 'm3' AS den, NULL AS co2, NULL AS sub, 'น้ำประปา' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C3_DIESEL_UPS' AS cat, 'CO2' AS gas, 0.35220000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, 'การได้มาของน้ำมันดีเซล' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C3_GASOLINE_UPS' AS cat, 'CO2' AS gas, 0.40240000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, 'การได้มาของน้ำมันเบนซิน' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C3_ELEC_UPS' AS cat, 'CO2' AS gas, 0.09870000 AS val, 'kgCO2eq/kWh' AS unit, 'kgCO2eq' AS num, 'kWh' AS den, NULL AS co2, NULL AS sub, 'การได้มาของไฟฟ้า' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C3_LPG_UPS' AS cat, 'CO2' AS gas, 0.85820000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, 'การได้มาของ LPG' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C3_ETHANOL_UPS' AS cat, 'CO2' AS gas, 0.39620000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, 'การได้มาของเอทานอล (Ethanol acquisition)' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C5_WASTE_LANDFILL' AS cat, 'CO2' AS gas, 0.79330000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, 'ขยะทั่วไป (กำจัดด้วยวิธีฝังกลบ)' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C5_WASTE_INCIN' AS cat, 'CO2' AS gas, 1.21000000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, 'ขยะอันตราย (กำจัดด้วยวิธีเผาทำลาย)' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C5_SLUDGE' AS cat, 'CO2' AS gas, 0.98280000 AS val, 'kgCO2eq/ton' AS unit, 'kgCO2eq' AS num, 'ton' AS den, NULL AS co2, NULL AS sub, 'กากตะกอน (ส่วนที่นำไปฝังกลบ)' AS name_th, NULL AS purpose, 'IPCC_AR5' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C5_EXCAVATOR' AS cat, 'CO2' AS gas, 2.97930000 AS val, 'kgCO2eq/litre' AS unit, 'kgCO2eq' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, 'รถแบคโฮ/รถขุด ดีเซล (off-road)' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C2_BUILDING' AS cat, 'CO2' AS gas, 0.22920000 AS val, 'kgCO2eq/THB' AS unit, 'kgCO2eq' AS num, 'THB' AS den, NULL AS co2, NULL AS sub, 'อาคาร' AS name_th, NULL AS purpose, 'USEEIO_V1' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C2_BUILDING' AS cat, 'CO2' AS gas, 0.22920000 AS val, 'kgCO2eq/THB' AS unit, 'kgCO2eq' AS num, 'THB' AS den, NULL AS co2, NULL AS sub, 'สิ่งปรับปรุงอาคาร' AS name_th, NULL AS purpose, 'USEEIO_V1' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C2_OFFICE_EQUIP' AS cat, 'CO2' AS gas, 0.35740000 AS val, 'kgCO2eq/THB' AS unit, 'kgCO2eq' AS num, 'THB' AS den, NULL AS co2, NULL AS sub, 'อุปกรณ์สำนักงาน (เครื่องมือ, อุปกรณ์ตกแต่ง)' AS name_th, NULL AS purpose, 'USEEIO_V1' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C2_COMPUTER' AS cat, 'CO2' AS gas, 0.14600000 AS val, 'kgCO2eq/THB' AS unit, 'kgCO2eq' AS num, 'THB' AS den, NULL AS co2, NULL AS sub, 'คอมพิวเตอร์' AS name_th, NULL AS purpose, 'USEEIO_V1' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C2_SOFTWARE' AS cat, 'CO2' AS gas, 0.03980000 AS val, 'kgCO2eq/THB' AS unit, 'kgCO2eq' AS num, 'THB' AS den, NULL AS co2, NULL AS sub, 'โปรแกรมคอมพิวเตอร์ (ซอฟต์แวร์ระบบงาน)' AS name_th, NULL AS purpose, 'USEEIO_V1' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C2_VEHICLE_CAP' AS cat, 'CO2' AS gas, 0.40860000 AS val, 'kgCO2eq/THB' AS unit, 'kgCO2eq' AS num, 'THB' AS den, NULL AS co2, NULL AS sub, 'ยานพาหนะ (Pickup trucks, vans, SUVs)' AS name_th, NULL AS purpose, 'USEEIO_V1' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C5_TRANSPORT_TKM' AS cat, 'CO2' AS gas, 0.04750000 AS val, 'kgCO2eq/tkm' AS unit, 'kgCO2eq' AS num, 'tkm' AS den, NULL AS co2, NULL AS sub, 'รถบรรทุกขยะ 6 ล้อ (0% Loading)' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C5_TRANSPORT_KM' AS cat, 'CO2' AS gas, 0.49230000 AS val, 'kgCO2eq/km' AS unit, 'kgCO2eq' AS num, 'km' AS den, NULL AS co2, NULL AS sub, 'รถบรรทุกขยะ 6 ล้อ (100% Loading)' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C5_TRANSPORT_TKM' AS cat, 'CO2' AS gas, 0.21540000 AS val, 'kgCO2eq/tkm' AS unit, 'kgCO2eq' AS num, 'tkm' AS den, NULL AS co2, NULL AS sub, 'รถบรรทุกขยะรีไซเคิล 4 ล้อ (100% Loading)' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C5_TRANSPORT_KM' AS cat, 'CO2' AS gas, 0.24150000 AS val, 'kgCO2eq/km' AS unit, 'kgCO2eq' AS num, 'km' AS den, NULL AS co2, NULL AS sub, 'รถบรรทุกขยะรีไซเคิล 4 ล้อ (0% Loading)' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C5_TRANSPORT_TKM' AS cat, 'CO2' AS gas, 0.05330000 AS val, 'kgCO2eq/tkm' AS unit, 'kgCO2eq' AS num, 'tkm' AS den, NULL AS co2, NULL AS sub, 'รถขนส่งกากตะกอน 10 ล้อ (100% Loading)' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C5_TRANSPORT_KM' AS cat, 'CO2' AS gas, 0.59000000 AS val, 'kgCO2eq/km' AS unit, 'kgCO2eq' AS num, 'km' AS den, NULL AS co2, NULL AS sub, 'รถขนส่งกากตะกอน 10 ล้อ (0% Loading)' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C7_COMMUTE_DIESEL' AS cat, 'CO2' AS gas, 2.74060000 AS val, 'kgCO2eq/litre' AS unit, 'kgCO2eq' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, 'รถกระบะ/รถยนต์/รถเมล์ (Diesel)' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C7_COMMUTE_GAS' AS cat, 'CO2' AS gas, 2.23940000 AS val, 'kgCO2eq/litre' AS unit, 'kgCO2eq' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, 'รถยนต์/รถจักรยานยนต์ (Gasoline)' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C7_COMMUTE_LPG' AS cat, 'CO2' AS gas, 3.20490000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, 'รถยนต์ส่วนบุคคล (LPG)' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C7_COMMUTE_EV' AS cat, 'CO2' AS gas, 0.49990000 AS val, 'kgCO2eq/kWh' AS unit, 'kgCO2eq' AS num, 'kWh' AS den, NULL AS co2, NULL AS sub, 'รถยนต์ไฟฟ้า (EV)' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C7_COMMUTE_CNG' AS cat, 'CO2' AS gas, 2.60900000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, 'รถ Taxi (CNG)' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C7_COMMUTE_DIESEL' AS cat, 'CO2' AS gas, 2.74060000 AS val, 'kgCO2eq/litre' AS unit, 'kgCO2eq' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, 'การเดินทางของลูกค้า (Diesel)' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C7_COMMUTE_GAS' AS cat, 'CO2' AS gas, 2.23940000 AS val, 'kgCO2eq/litre' AS unit, 'kgCO2eq' AS num, 'litre' AS den, NULL AS co2, NULL AS sub, 'การเดินทางของลูกค้า (Gasoline)' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
  UNION ALL
  SELECT 'S3C7_COMMUTE_CNG' AS cat, 'CO2' AS gas, 2.60900000 AS val, 'kgCO2eq/kg' AS unit, 'kgCO2eq' AS num, 'kg' AS den, NULL AS co2, NULL AS sub, 'การเดินทางของลูกค้า (CNG)' AS name_th, NULL AS purpose, 'TGO_CFP_2565' AS src, '2022-07-01' AS eff_from, NULL AS until, 1 AS is_def
) r
JOIN ef_categories c ON c.category_code = r.cat
JOIN gas_types g ON g.gas_code = r.gas;

-- Total rows: 257
